#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

unsigned int c_dotproduct(int Q, int len, unsigned int *vecA, unsigned int *vecB)
{
	// define your output to be able to keep the 64-bit value that will be generated by mul, vecA and vecB
	// vecA and vecB are 32-bit unsigned int and the multiplication resul can be 64-bit
	// you need to typecast these vectors to a 64bit values
	/* write your code here */

	unsigned long long int accumulator = 0;
	for(int i = 0; i < len; i++) {
		accumulator += (uint64_t)vecA[i] * (uint64_t)vecB[i];
	}
	// you need to do the multiply-accumulate operation len times
	return (accumulator >> Q); // return the accumulated result, but remember that this is fixed point and should be divided by Q ( >> Q)
}

